name: C# Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format on Backend/Balcao-API
        run: dotnet format ./Backend/Balcao-API/Balcao-API.csproj --verbosity diagnostic

      - name: Run dotnet format on Backend/Balcao.Domain
        run: dotnet format ./Backend/Balcao.Domain/Balcao.Domain.csproj --verbosity diagnostic

      - name: Run dotnet format on Backend/Balcao.Infrastructure
        run: dotnet format ./Backend/Balcao.Infrastructure/Balcao.Infrastructure.csproj --verbosity diagnostic

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Apply code formatting with dotnet format"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'push' || github.actor != 'github-actions[bot]' # Prevent infinite loop
