name: C# Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format on Backend/Balcao-API
        run: dotnet format ./Backend/Balcao-API/Balcao-API.csproj --verbosity diagnostic

      - name: Run dotnet format on Backend/Balcao.Domain
        run: dotnet format ./Backend/Balcao.Domain/Balcao.Domain.csproj --verbosity diagnostic

      - name: Run dotnet format on Backend/Balcao.Infrastructure
        run: dotnet format ./Backend/Balcao.Infrastructure/Balcao.Infrastructure.csproj --verbosity diagnostic

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check if any changes were made
        run: |
          git diff --exit-code || echo "Changes detected" > result.txt
        id: check_changes

      - name: Commit and push changes
        run: |
         if [ -f result.txt ]; then
  # Get the current branch name
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  # If in detached HEAD state, use the HEAD reference
  if [ "$CURRENT_BRANCH" == "HEAD" ]; then
    echo "We're in a detached HEAD state, but we will commit to the branch we came from."
    # Set the branch as 'main' or any branch you want to commit to
    CURRENT_BRANCH=$(git reflog show --no-abbrev | head -n 1 | awk '{print $NF}')
  fi

  # Stage and commit the changes
  git add .
  git commit -m "Apply code formatting with dotnet format"

  # Push the changes to the same branch
  git push origin "$CURRENT_BRANCH"
else
  echo "No changes to commit."
fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'push' && github.actor != 'github-actions[bot]'
